### ISSUE TITLE
头部 view 加图片

### ISSUE THREAD

**Issue by honeybeeSwinging** [xuhongfei/HFNavigationController#1]

**Comment by honeybeeSwinging** [comment]
你好，我想在头部 view 上面不仅是文字还要图片的这个怎么做呢？你的代码没有注释真是不太好理解

**Comment by xuhongfei** [comment]
文字的设置是通过设置相应的控制器的title来实现的，你可以设置对应控制器的TitleView，里面文字、图片，你可以按自己的需求来
